import { Router, Request, Response } from "express";
import { success, successList, error } from "../utils/response.js";
import { createPedidoSchema, updatePedidoSchema } from "../schemas/pedido.js";
import * as pedidosService from "../services/pedidosService.js";

const router = Router();

/**
 * @openapi
 * /api/pedidos:
 *   get:
 *     summary: List all pedidos
 *     tags: [Pedidos]
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *         description: Filter by status
 *       - in: query
 *         name: ticket
 *         schema:
 *           type: string
 *         description: Filter by ticket
 *       - in: query
 *         name: oab
 *         schema:
 *           type: string
 *         description: Filter by OAB number
 *     responses:
 *       200:
 *         description: List of pedidos
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ListResponse'
 *                 - properties:
 *                     data:
 *                       items:
 *                         $ref: '#/components/schemas/Pedido'
 */
router.get("/", async (req: Request, res: Response) => {
  try {
    const filters = {
      status: req.query.status as string | undefined,
      ticket: req.query.ticket as string | undefined,
      oab: req.query.oab as string | undefined,
    };
    const pedidos = await pedidosService.getAllPedidos(filters);
    res.json(successList(pedidos));
  } catch (err) {
    console.error("Error fetching pedidos:", err);
    res.status(500).json(error("Failed to fetch pedidos"));
  }
});

/**
 * @openapi
 * /api/pedidos/{uuid}:
 *   get:
 *     summary: Get pedido by UUID
 *     tags: [Pedidos]
 *     parameters:
 *       - in: path
 *         name: uuid
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Pedido UUID
 *     responses:
 *       200:
 *         description: Pedido found
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessResponse'
 *                 - properties:
 *                     data:
 *                       $ref: '#/components/schemas/Pedido'
 *       404:
 *         description: Pedido not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.get("/:uuid", async (req: Request, res: Response) => {
  try {
    const pedido = await pedidosService.getPedidoById(req.params.uuid);
    if (!pedido) {
      return res.status(404).json(error("Pedido not found"));
    }
    res.json(success(pedido));
  } catch (err) {
    console.error("Error fetching pedido:", err);
    res.status(500).json(error("Failed to fetch pedido"));
  }
});

/**
 * @openapi
 * /api/pedidos:
 *   post:
 *     summary: Create a new pedido
 *     tags: [Pedidos]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/CreatePedido'
 *     responses:
 *       201:
 *         description: Pedido created (UUID generated by API)
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessResponse'
 *                 - properties:
 *                     data:
 *                       $ref: '#/components/schemas/Pedido'
 *       400:
 *         description: Validation error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.post("/", async (req: Request, res: Response) => {
  const parsed = createPedidoSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json(error(parsed.error.errors[0].message));
  }

  try {
    const pedido = await pedidosService.createPedido(parsed.data);
    res.status(201).json(success(pedido));
  } catch (err) {
    console.error("Error creating pedido:", err);
    res.status(500).json(error("Failed to create pedido"));
  }
});

/**
 * @openapi
 * /api/pedidos/{uuid}:
 *   put:
 *     summary: Update a pedido (partial)
 *     tags: [Pedidos]
 *     parameters:
 *       - in: path
 *         name: uuid
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Pedido UUID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/CreatePedido'
 *     responses:
 *       200:
 *         description: Pedido updated
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessResponse'
 *                 - properties:
 *                     data:
 *                       $ref: '#/components/schemas/Pedido'
 *       404:
 *         description: Pedido not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.put("/:uuid", async (req: Request, res: Response) => {
  const parsed = updatePedidoSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json(error(parsed.error.errors[0].message));
  }

  try {
    const pedido = await pedidosService.updatePedido(
      req.params.uuid,
      parsed.data
    );
    res.json(success(pedido));
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to update pedido";
    const status = message === "Pedido not found" ? 404 : 500;
    console.error("Error updating pedido:", err);
    res.status(status).json(error(message));
  }
});

/**
 * @openapi
 * /api/pedidos/{uuid}:
 *   delete:
 *     summary: Remove a pedido
 *     tags: [Pedidos]
 *     parameters:
 *       - in: path
 *         name: uuid
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Pedido UUID
 *     responses:
 *       200:
 *         description: Pedido deleted
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SuccessResponse'
 *       404:
 *         description: Pedido not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.delete("/:uuid", async (req: Request, res: Response) => {
  try {
    await pedidosService.deletePedido(req.params.uuid);
    res.json(success({ message: "Pedido deleted" }));
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to delete pedido";
    const status = message === "Pedido not found" ? 404 : 500;
    console.error("Error deleting pedido:", err);
    res.status(status).json(error(message));
  }
});

export default router;
