import fs from "node:fs";
import path from "node:path";
import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "CAAB API Certificação",
      version: "1.0.0",
      description:
        'REST API (CRUD) for "Primeira Certificação" Google Spreadsheet',
    },
    components: {
      securitySchemes: {
        basicAuth: {
          type: "http",
          scheme: "basic",
        },
      },
      schemas: {
        Ticket: {
          type: "object",
          properties: {
            ticket: { type: "string", example: "12345678900" },
            status: {
              type: "string",
              example: "",
              description:
                'Ticket status: "" (available), "Atribuído" (assigned), "Cancelado" (cancelled)',
            },
          },
        },
        Order: {
          type: "object",
          properties: {
            uuid: {
              type: "string",
              format: "uuid",
              example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            },
            ticket: { type: "string", example: "68637750800" },
            numero_oab: { type: "string", example: "123456" },
            nome_completo: { type: "string", example: "João da Silva" },
            subsecao: { type: "string", example: "São Paulo" },
            data_solicitacao: { type: "string", example: "2026-02-13" },
            data_liberacao: { type: "string", example: "2026-02-20" },
            status: { type: "string", example: "aprovado" },
            anotacoes: { type: "string", example: "Primeira certificação" },
          },
        },
        CreateOrder: {
          type: "object",
          required: ["nome_completo"],
          properties: {
            nome_completo: { type: "string", example: "João da Silva" },
            numero_oab: { type: "string", example: "123456" },
            subsecao: { type: "string", example: "São Paulo" },
            data_solicitacao: {
              type: "string",
              pattern: "^\\d{4}-\\d{2}-\\d{2}$",
              example: "2026-02-13",
            },
            data_liberacao: {
              type: "string",
              pattern: "^\\d{4}-\\d{2}-\\d{2}$",
              example: "2026-02-20",
            },
            status: { type: "string", example: "pendente" },
            anotacoes: { type: "string", example: "Primeira certificação" },
          },
        },
        SuccessResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: true },
            data: { type: "object" },
          },
        },
        ListResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: true },
            count: { type: "integer", example: 5 },
            data: { type: "array", items: {} },
          },
        },
        ErrorResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: false },
            error: { type: "string", example: "Error message" },
          },
        },
      },
    },
    security: [{ basicAuth: [] }],
  },
  apis: ["./src/routes/*.ts"],
};

const spec = swaggerJsdoc(options);

const output = `// Auto-generated by scripts/generate-openapi.ts — do not edit manually.
// Run \`pnpm generate:spec\` to regenerate.

const swaggerSpec = ${JSON.stringify(spec, null, 2)} as const;

export default swaggerSpec;
`;

const outPath = path.resolve("src/generated/swagger-spec.ts");
fs.writeFileSync(outPath, output, "utf-8");
console.log(`OpenAPI spec written to ${outPath}`);
